# Generated by Django 6.0.3 on 2026-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_preference',
            field=models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar')], default='EGP', max_length=3),
        ),
    ]
