# Generated by Django 6.0.3 on 2026-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_currency_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_mode_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('comfort', 'Comfort'), ('compact', 'Compact')], default='comfort', max_length=10),
        ),
    ]
