# Generated by Django 6.0.3 on 2026-03-21 21:01

import attrition.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('predictionID', models.CharField(default=attrition.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('riskScore', models.FloatField()),
                ('riskLevel', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('feedbackFormID', models.CharField(blank=True, max_length=50, null=True)),
                ('predictedAt', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='attrition_predictions', to='feedback.employee')),
            ],
            options={
                'db_table': 'AttritionPrediction',
                'ordering': ['-predictedAt'],
            },
        ),
    ]
