# Generated by Django 6.0.3 on 2026-04-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attritionprediction',
            name='confidenceScore',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attritionprediction',
            name='modelVersion',
            field=models.CharField(blank=True, default='xgboost-attrition-v2-governed', max_length=100),
        ),
        migrations.AddField(
            model_name='attritionprediction',
            name='predictionSource',
            field=models.CharField(blank=True, default='xgboost', max_length=40),
        ),
        migrations.AddField(
            model_name='attritionprediction',
            name='reviewRequired',
            field=models.BooleanField(default=True),
        ),
    ]
