# Generated by Django 6.0.3 on 2026-03-21 21:01

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('employeeID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'feedback_admin',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('yearsAtCompany', models.IntegerField(blank=True, null=True)),
                ('monthlyIncome', models.IntegerField(blank=True, null=True)),
                ('performanceRating', models.IntegerField(blank=True, null=True)),
                ('numberOfPromotions', models.IntegerField(blank=True, null=True)),
                ('overtime', models.BooleanField(blank=True, null=True)),
                ('educationLevel', models.IntegerField(blank=True, choices=[(1, 'High School'), (2, 'Associate Degree'), (3, "Bachelor's Degree"), (4, "Master's Degree"), (5, 'PhD')], null=True)),
                ('numberOfDependents', models.IntegerField(blank=True, null=True)),
                ('jobLevel', models.IntegerField(blank=True, choices=[(1, 'Entry'), (2, 'Mid'), (3, 'Senior')], null=True)),
                ('companySize', models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], null=True)),
                ('companyTenure', models.IntegerField(blank=True, null=True)),
                ('remoteWork', models.BooleanField(blank=True, null=True)),
                ('maritalStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'feedback_employee',
            },
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('formID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdByAdminID', models.ForeignKey(blank=True, db_column='createdByAdminID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to='feedback.adminuser')),
            ],
            options={
                'db_table': 'FeedbackForm',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('questionID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('questionText', models.CharField(max_length=300)),
                ('fieldType', models.CharField(choices=[('score_1_4', 'Score 1-4'), ('boolean', 'Yes / No'), ('decimal', 'Decimal Number')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('formID', models.ForeignKey(db_column='formID', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'db_table': 'FeedbackQuestion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('submissionID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('employeeID', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='feedback.employee')),
                ('formID', models.ForeignKey(db_column='formID', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='feedback.feedbackform')),
            ],
            options={
                'db_table': 'FeedbackSubmission',
                'unique_together': {('formID', 'employeeID')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('answerID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('scoreValue', models.IntegerField(blank=True, null=True)),
                ('booleanValue', models.BooleanField(blank=True, null=True)),
                ('decimalValue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackquestion')),
                ('submissionID', models.ForeignKey(db_column='submissionID', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbacksubmission')),
            ],
            options={
                'db_table': 'FeedbackAnswer',
                'unique_together': {('submissionID', 'questionID')},
            },
        ),
    ]
