# Generated by Django 6.0.3 on 2026-03-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_employee_department_employee_jobtitle_employee_team'),
    ]

    operations = []
