# Generated by Django 6.0.3 on 2026-03-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_employee_department_employee_jobtitle_employee_team'),
    ]

    operations = [
        migrations.AddField(model_name='employee', name='age',                field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='gender',             field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
        migrations.AddField(model_name='employee', name='yearsAtCompany',     field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='monthlyIncome',      field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='performanceRating',  field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='numberOfPromotions', field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='overtime',           field=models.BooleanField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='educationLevel',     field=models.IntegerField(blank=True, choices=[(1, 'High School'), (2, 'Associate Degree'), (3, "Bachelor's Degree"), (4, "Master's Degree"), (5, 'PhD')], null=True)),
        migrations.AddField(model_name='employee', name='numberOfDependents', field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='jobLevel',           field=models.IntegerField(blank=True, choices=[(1, 'Entry'), (2, 'Mid'), (3, 'Senior')], null=True)),
        migrations.AddField(model_name='employee', name='companySize',        field=models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], null=True)),
        migrations.AddField(model_name='employee', name='companyTenure',      field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='remoteWork',         field=models.BooleanField(blank=True, null=True)),
        migrations.AddField(model_name='employee', name='maritalStatus',      field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True)),
    ]
