# Generated by Django 6.0.3 on 2026-04-02 21:16

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_shift_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAnnouncement',
            fields=[
                ('policyID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('Policy', 'Policy'), ('Announcement', 'Announcement')], default='Policy', max_length=20)),
                ('audience', models.CharField(choices=[('All Employees', 'All Employees'), ('Managers', 'Managers'), ('Team Leaders', 'Team Leaders')], default='All Employees', max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Acknowledged', 'Acknowledged')], default='Draft', max_length=20)),
                ('effectiveDate', models.DateField(blank=True, null=True)),
                ('acknowledgedByIDs', models.JSONField(blank=True, default=list)),
                ('acknowledgementNotes', models.JSONField(blank=True, default=dict)),
                ('acknowledgedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PolicyAnnouncement',
                'ordering': ['-effectiveDate', '-createdAt'],
            },
        ),
    ]
