# Generated by Django 6.0.3 on 2026-04-02 21:41

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_policyannouncement_employee_companysize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionAward',
            fields=[
                ('awardID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Achievement', 'Achievement'), ('Appreciation', 'Appreciation'), ('Innovation', 'Innovation'), ('Teamwork', 'Teamwork'), ('Leadership', 'Leadership')], default='Achievement', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('recognitionDate', models.DateField()),
                ('recognizedBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='recognition_awards', to='feedback.employee')),
            ],
            options={
                'db_table': 'RecognitionAward',
                'ordering': ['-recognitionDate', '-createdAt'],
            },
        ),
    ]
