# Generated by Django 6.0.3 on 2026-04-02 21:56

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_employee_companysize_employee_companytenure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('enrollmentID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('benefitName', models.CharField(max_length=160)),
                ('benefitType', models.CharField(choices=[('Medical', 'Medical'), ('Dental', 'Dental'), ('Retirement', 'Retirement'), ('Transportation', 'Transportation'), ('Wellness', 'Wellness')], default='Medical', max_length=30)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('coverageLevel', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Enrolled', 'Enrolled'), ('Waived', 'Waived')], default='Pending', max_length=20)),
                ('monthlyCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employeeContribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effectiveDate', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employeeNote', models.TextField(blank=True)),
                ('acknowledgedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='benefit_enrollments', to='feedback.employee')),
            ],
            options={
                'db_table': 'BenefitEnrollment',
                'ordering': ['-effectiveDate', '-createdAt'],
            },
        ),
    ]
