# Generated by Django 6.0.3 on 2026-04-02 22:16

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_employee_companysize_employee_companytenure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('claimID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Meals', 'Meals'), ('Supplies', 'Supplies'), ('Training', 'Training'), ('Other', 'Other')], default='Other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenseDate', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Reimbursed', 'Reimbursed')], default='Submitted', max_length=20)),
                ('reviewNote', models.TextField(blank=True)),
                ('reviewedBy', models.CharField(blank=True, max_length=150)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='feedback.employee')),
            ],
            options={
                'db_table': 'ExpenseClaim',
                'ordering': ['-expenseDate', '-createdAt'],
            },
        ),
    ]
