# Generated by Django 6.0.3 on 2026-04-02 22:40

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_employee_companysize_employee_companytenure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('requestID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('documentType', models.CharField(choices=[('Salary Certificate', 'Salary Certificate'), ('Employment Letter', 'Employment Letter'), ('Experience Letter', 'Experience Letter'), ('ID Verification', 'ID Verification')], default='Employment Letter', max_length=30)),
                ('purpose', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Issued', 'Issued'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('reviewNote', models.TextField(blank=True)),
                ('issuedBy', models.CharField(blank=True, max_length=150)),
                ('issuedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='feedback.employee')),
            ],
            options={
                'db_table': 'DocumentRequest',
                'ordering': ['-createdAt'],
            },
        ),
    ]
