# Generated by Django 6.0.3 on 2026-04-02 22:55

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_employee_companysize_employee_companytenure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticketID', models.CharField(default=feedback.models.gen_id, max_length=50, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Payroll', 'Payroll'), ('Benefits', 'Benefits'), ('Policy', 'Policy'), ('General', 'General')], default='General', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('resolutionNote', models.TextField(blank=True)),
                ('assignedTo', models.CharField(blank=True, max_length=150)),
                ('resolvedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employeeID', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='feedback.employee')),
            ],
            options={
                'db_table': 'SupportTicket',
                'ordering': ['-updatedAt', '-createdAt'],
            },
        ),
    ]
