# Generated by Django 6.0.3 on 2026-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_policyannouncement_reminder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='companySize',
            field=models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='companyTenure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
