# Generated by Django 6.0.3 on 2026-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_employee_companysize_employee_companytenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency_preference',
            field=models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar')], default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='currency',
            field=models.CharField(choices=[('EGP', 'Egyptian Pound'), ('USD', 'US Dollar')], default='EGP', max_length=3),
        ),
    ]
